export const EVENT_SET_ACTIVE = 'EVENT_SET_ACTIVE';
export const EVENT_ADD_NEW = 'EVENT_ADD_NEW';
export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_CLEAR_EVENT = 'EVENT_CLEAR_EVENT';
export const EVENT_UPDATED = 'EVENT_UPDATED';
export const EVENT_DELETED = 'EVENT_DELETED';